name: CPP tests

on: [ push, pull_request ]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 1
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 1
          sudo update-alternatives --set gcc /usr/bin/gcc-14
          sudo update-alternatives --set g++ /usr/bin/g++-14

      - name: Conan
        run: |
          pip install conan
          conan profile detect --force
          conan install ${{github.workspace}}/model --output-folder=${{github.workspace}}/model/build/conan --build=missing --settings=build_type=${{env.BUILD_TYPE}}

      - name: Configure CMake
        run: cmake ${{github.workspace}}/model -B ${{github.workspace}}/model/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/model/build/conan/conan_toolchain.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/model/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/model/build
        run: ctest -C ${{env.BUILD_TYPE}}
