name: Integration tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install GCC
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 1
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 1
          sudo update-alternatives --set gcc /usr/bin/gcc-14
          sudo update-alternatives --set g++ /usr/bin/g++-14

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry to use local virtual environments
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies with Poetry
        run: poetry install

      - name: Install Conan
        run: pip install conan

      - name: Detect Conan profile
        run: conan profile detect

      - name: Build and install creepers_lib with Conan
        run: |
          mkdir -p model/build
          cd model/build
          conan install .. --build=missing
          conan build ..

      - name: Add local build to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/model/build/install/lib:$PYTHONPATH" >> $GITHUB_ENV

      - name: Verify creepers_lib import
        run: poetry run python -c "import creepers_lib"

      - name: Build project
        run: poetry run build

      - name: Run tests
        run: poetry run python -m pytest test
