name: Check code

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Install pre-commit hooks
        run: |
          pre-commit install
          pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --color always --verbose --show-diff-on-failure
