name: Check code

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: |
          poetry run pre-commit install
          poetry run pre-commit run --all-files --color always --verbose --show-diff-on-failure
